import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar configuration with sections
  docsSidebar: [
    // Overview at the top
    {
      type: 'doc',
      id: 'devdocs/overview',
      label: 'Overview',
    },
    
    // Builders section heading
    {
      type: 'html',
      value: '<span class="sidebar-section-title">#BUIDLers</span>',
      className: 'sidebar-section-header',
    },
    
    // Builders section items
    {
      type: 'category',
      label: 'Quick Start',
      link: {
        type: 'doc',
        id: 'devdocs/quick-start/index',
      },
      items: [
        {
          type: 'doc',
          id: 'devdocs/quick-start/best-practices',
          label: 'Best Practices',
        },
      ],
    },
    {
      type: 'category',
      label: 'Cofhejs',
      link: {
        type: 'doc',
        id: 'devdocs/cofhejs/index',
      },
      items: [
        {
          type: 'doc',
          id: 'devdocs/cofhejs/encryption-operations',
          label: 'Encryption',
        },
        {
          type: 'doc',
          id: 'devdocs/cofhejs/sealing-unsealing',
          label: 'Sealing & Unsealing',
        },
        {
          type: 'doc',
          id: 'devdocs/cofhejs/permits-management',
          label: 'Permits Management',
        },
        {
          type: 'doc',
          id: 'devdocs/cofhejs/error-handling',
          label: 'Error Handling',
        },
      ],
    },
    {
      type: 'category',
      label: 'FHE Library',
      link: {
        type: 'doc',
        id: 'devdocs/fhe-library/index',
      },
      items: [
        {
          type: 'doc',
          id: 'devdocs/fhe-library/inputs',
          label: 'Inputs',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/trivial-encryption',
          label: 'Trivial Encryption',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/data-evaluation',
          label: 'Data Evaluation',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/fhe-encrypted-operations',
          label: 'FHE Encrypted Operations',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/select-vs-ifelse',
          label: 'Conditions',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/acl-mechanism',
          label: 'ACL Mechanism',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/decryption-operations',
          label: 'Decryption Operations',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/randomness',
          label: 'Randomness',
        },
        {
          type: 'doc',
          id: 'devdocs/fhe-library/gas-and-benchmarks',
          label: 'Gas and Benchmarks',
        },
      ],
    },
    {
      type: 'category',
      label: 'FHERC',
      link: {
        type: 'doc',
        id: 'devdocs/fherc/index',
      },
      items: [
        {
          type: 'doc',
          id: 'devdocs/fherc/fherc20',
          label: 'FHERC20 Token Standard',
        },
      ],
    },
    {
      type: 'category',
      label: 'SolidityAPI',
      link: {
        type: 'generated-index',
        description: 'Solidity API reference',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/solidity-api',
        },
      ],
    },
    {
      type: 'doc',
      id: 'devdocs/sdk/index',
      label: 'SDK',
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'indexes/tutorials',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'devdocs/tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Key Considerations',
      link: {
        type: 'doc',
        id: 'devdocs/pay-attention/index',
      },
      items: [
        {
          type: 'doc',
          id: 'devdocs/pay-attention/component-compatibility',
        },
      ],
    },
    {
      type: 'doc',
      id: 'devdocs/support-and-feedback',
      label: 'Support & Feedback',
    },
    
    // Deep Dive section heading
    {
      type: 'html',
      value: '<span class="sidebar-section-title">Deep Dive</span>',
      className: 'sidebar-section-header',
    },
    
    // Deep Dive section items
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'doc',
        id: 'devdocs/architecture/index',
      },
      items: [
        {
          type: 'category',
          label: 'Libraries',
          items: [
            {
              type: 'autogenerated',
              dirName: 'devdocs/architecture/user-facing-utilities',
            },
          ],
        },
        {
          type: 'category',
          label: 'CoFHE Components',
          items: [
            {
              type: 'autogenerated',
              dirName: 'devdocs/architecture/internal-utilities',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Flows',
          items: [
            {
              type: 'autogenerated',
              dirName: 'devdocs/architecture/data-flows',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'devdocs/future-plans',
      label: 'Future Plans',
    },
    {
      type: 'doc',
      id: 'devdocs/research-and-publications',
      label: 'Research in Fhenix',
    },
  ],
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
